"""Subjects and the concept graph.

Plain data so the slugs — which profiles, deep links and the interest map are
all keyed by — are reviewable in a diff.

Concepts are ordered within a subject roughly by when a student meets them,
and `difficulty` is 1 (foundational) to 5 (advanced). The recommender uses
that number to keep a suggestion one step ahead of the learner rather than ten,
so it is a real input and not decoration.
"""

from __future__ import annotations

SUBJECTS: list[dict] = [
    {"slug": "mathematics", "name": "Mathematics", "icon": "function", "accent": "#4C6FFF",
     "description": "Algebra, geometry, calculus and the reasoning underneath them."},
    {"slug": "physics", "name": "Physics", "icon": "atom", "accent": "#00A9A5",
     "description": "How the physical world behaves, and why."},
    {"slug": "chemistry", "name": "Chemistry", "icon": "flask", "accent": "#F2704B",
     "description": "Matter, reactions, and the arithmetic that governs them."},
    {"slug": "biology", "name": "Biology", "icon": "leaf", "accent": "#38A169",
     "description": "Cells, genes, bodies and ecosystems."},
    {"slug": "computer-science", "name": "Computer Science",
     "icon": "chevron.left.forwardslash.chevron.right", "accent": "#7C5CFF",
     "description": "Programming, algorithms, data and the machines that run them."},
    {"slug": "economics", "name": "Economics", "icon": "chart.line.uptrend.xyaxis",
     "accent": "#D69E2E", "description": "Choices, incentives, markets and money."},
    {"slug": "history", "name": "History", "icon": "clock", "accent": "#B7791F",
     "description": "What happened, and the arguments about what it meant."},
    {"slug": "geography", "name": "Geography", "icon": "globe.americas", "accent": "#2C7A7B",
     "description": "Physical systems, human systems, and the maps of both."},
    {"slug": "psychology", "name": "Psychology", "icon": "brain", "accent": "#D53F8C",
     "description": "How minds work, and how we found out."},
    {"slug": "languages", "name": "Languages", "icon": "character.bubble", "accent": "#DD6B20",
     "description": "Grammar, vocabulary and the habits of fluent use."},
    {"slug": "literature", "name": "Literature", "icon": "book", "accent": "#805AD5",
     "description": "Reading closely, and writing about what you read."},
    {"slug": "art", "name": "Art & Design", "icon": "paintbrush", "accent": "#E53E3E",
     "description": "Visual language, composition and design history."},
    {"slug": "business", "name": "Business", "icon": "briefcase", "accent": "#319795",
     "description": "How organisations are built, funded and run."},
    {"slug": "engineering", "name": "Engineering", "icon": "gearshape.2", "accent": "#4A5568",
     "description": "Designing things that have to work."},
]

# subject slug -> [(concept slug, name, difficulty)]
CONCEPTS: dict[str, list[tuple[str, str, int]]] = {
    "mathematics": [
        ("variables-expressions", "Variables and Expressions", 1),
        ("linear-equations", "Linear Equations", 1),
        ("quadratic-equations", "Quadratic Equations", 2),
        ("functions", "Functions", 2),
        ("polynomials", "Polynomials", 2),
        ("trigonometric-ratios", "Trigonometric Ratios", 2),
        ("exponentials-logarithms", "Exponentials and Logarithms", 3),
        ("sequences-series", "Sequences and Series", 3),
        ("limits", "Limits", 3),
        ("derivatives", "Derivatives", 3),
        ("chain-rule", "The Chain Rule", 4),
        ("integrals", "Integrals", 4),
        ("differential-equations", "Differential Equations", 5),
        ("vectors", "Vectors", 3),
        ("matrices", "Matrices", 3),
        ("eigenvalues", "Eigenvalues and Eigenvectors", 5),
        ("probability", "Probability", 2),
        ("distributions", "Probability Distributions", 3),
        ("hypothesis-testing", "Hypothesis Testing", 4),
        ("bayes-theorem", "Bayes' Theorem", 4),
    ],
    "physics": [
        ("units-measurement", "Units and Measurement", 1),
        ("kinematics", "Kinematics", 2),
        ("newtons-laws", "Newton's Laws", 2),
        ("momentum", "Momentum", 3),
        ("work-energy", "Work and Energy", 3),
        ("circular-motion", "Circular Motion", 3),
        ("gravitation", "Gravitation", 3),
        ("waves", "Waves", 3),
        ("optics", "Optics", 3),
        ("electric-fields", "Electric Fields", 4),
        ("current-resistance", "Current and Resistance", 3),
        ("ohms-law", "Ohm's Law", 2),
        ("magnetism", "Magnetism", 4),
        ("thermodynamics-laws", "Laws of Thermodynamics", 4),
        ("entropy", "Entropy", 4),
        ("special-relativity", "Special Relativity", 5),
        ("quantum-basics", "Quantum Basics", 5),
    ],
    "chemistry": [
        ("atomic-structure", "Atomic Structure", 1),
        ("periodic-trends", "Periodic Trends", 2),
        ("chemical-bonding", "Chemical Bonding", 2),
        ("moles-stoichiometry", "Moles and Stoichiometry", 2),
        ("reaction-types", "Reaction Types", 2),
        ("acids-bases", "Acids and Bases", 3),
        ("equilibrium", "Chemical Equilibrium", 4),
        ("thermochemistry", "Thermochemistry", 3),
        ("reaction-kinetics", "Reaction Kinetics", 4),
        ("electrochemistry", "Electrochemistry", 4),
        ("organic-functional-groups", "Organic Functional Groups", 3),
        ("reaction-mechanisms", "Reaction Mechanisms", 5),
    ],
    "biology": [
        ("cell-structure", "Cell Structure", 1),
        ("cell-transport", "Cell Transport", 2),
        ("photosynthesis", "Photosynthesis", 2),
        ("cellular-respiration", "Cellular Respiration", 3),
        ("mitosis-meiosis", "Mitosis and Meiosis", 2),
        ("dna-replication", "DNA Replication", 3),
        ("protein-synthesis", "Protein Synthesis", 3),
        ("mendelian-genetics", "Mendelian Genetics", 2),
        ("natural-selection", "Natural Selection", 2),
        ("homeostasis", "Homeostasis", 3),
        ("nervous-system", "The Nervous System", 3),
        ("immune-system", "The Immune System", 4),
        ("ecosystems", "Ecosystems", 2),
    ],
    "computer-science": [
        ("variables-types", "Variables and Types", 1),
        ("control-flow", "Control Flow", 1),
        ("functions-scope", "Functions and Scope", 2),
        ("arrays-lists", "Arrays and Lists", 2),
        ("hash-maps", "Hash Maps", 3),
        ("recursion", "Recursion", 3),
        ("big-o", "Big-O Notation", 3),
        ("sorting-algorithms", "Sorting Algorithms", 3),
        ("trees-graphs", "Trees and Graphs", 4),
        ("dynamic-programming", "Dynamic Programming", 5),
        ("databases-sql", "Databases and SQL", 3),
        ("http-apis", "HTTP and APIs", 2),
        ("version-control", "Version Control", 2),
        ("neural-networks", "Neural Networks", 4),
        ("backpropagation", "Backpropagation", 5),
        ("embeddings", "Embeddings", 4),
        ("recommendation-systems", "Recommendation Systems", 4),
    ],
    "economics": [
        ("scarcity-tradeoffs", "Scarcity and Trade-offs", 1),
        ("supply-demand", "Supply and Demand", 2),
        ("elasticity", "Elasticity", 3),
        ("market-structures", "Market Structures", 3),
        ("gdp", "GDP and National Income", 3),
        ("inflation", "Inflation", 3),
        ("monetary-policy", "Monetary Policy", 4),
        ("comparative-advantage", "Comparative Advantage", 3),
        ("game-theory-basics", "Game Theory Basics", 4),
    ],
    "history": [
        ("primary-sources", "Reading Primary Sources", 2),
        ("industrial-revolution", "The Industrial Revolution", 2),
        ("french-revolution", "The French Revolution", 3),
        ("world-war-one", "World War One", 3),
        ("world-war-two", "World War Two", 3),
        ("cold-war", "The Cold War", 3),
        ("decolonisation", "Decolonisation", 4),
        ("historiography", "Historiography", 5),
    ],
    "geography": [
        ("plate-tectonics", "Plate Tectonics", 2),
        ("weather-climate", "Weather and Climate", 2),
        ("water-cycle", "The Water Cycle", 1),
        ("urbanisation", "Urbanisation", 3),
        ("population-models", "Population Models", 3),
        ("climate-change", "Climate Change", 3),
    ],
    "psychology": [
        ("research-methods", "Research Methods", 2),
        ("memory-models", "Models of Memory", 3),
        ("classical-conditioning", "Classical Conditioning", 2),
        ("operant-conditioning", "Operant Conditioning", 2),
        ("cognitive-biases", "Cognitive Biases", 3),
        ("attachment", "Attachment", 3),
        ("stress-response", "The Stress Response", 3),
    ],
    "languages": [
        ("word-order", "Word Order", 1),
        ("verb-tenses", "Verb Tenses", 2),
        ("conditionals", "Conditionals", 3),
        ("collocations", "Collocations", 3),
        ("register-tone", "Register and Tone", 4),
    ],
    "literature": [
        ("close-reading", "Close Reading", 2),
        ("narrative-perspective", "Narrative Perspective", 3),
        ("metaphor-imagery", "Metaphor and Imagery", 2),
        ("thesis-statements", "Thesis Statements", 2),
        ("essay-structure", "Essay Structure", 2),
    ],
    "art": [
        ("composition", "Composition", 1),
        ("colour-theory", "Colour Theory", 2),
        ("perspective-drawing", "Perspective", 2),
        ("typography-basics", "Typography", 3),
        ("design-critique", "Design Critique", 3),
    ],
    "business": [
        ("business-models", "Business Models", 2),
        ("unit-economics", "Unit Economics", 3),
        ("marketing-funnels", "Marketing Funnels", 3),
        ("financial-statements", "Financial Statements", 4),
    ],
    "engineering": [
        ("free-body-diagrams", "Free Body Diagrams", 2),
        ("stress-strain", "Stress and Strain", 3),
        ("circuits", "Circuit Analysis", 3),
        ("control-systems", "Control Systems", 5),
        ("cad-basics", "CAD Basics", 2),
    ],
}

# Directed edges: (from, to, kind). Direction matters — derivatives lead to
# integrals, not the other way round — so each pair is stored once.
EDGES: list[tuple[str, str, str]] = [
    ("linear-equations", "quadratic-equations", "next"),
    ("quadratic-equations", "functions", "next"),
    ("functions", "limits", "next"),
    ("limits", "derivatives", "next"),
    ("derivatives", "chain-rule", "next"),
    ("derivatives", "integrals", "next"),
    ("chain-rule", "integrals", "related"),
    ("integrals", "differential-equations", "next"),
    ("functions", "exponentials-logarithms", "related"),
    ("vectors", "matrices", "next"),
    ("matrices", "eigenvalues", "next"),
    ("probability", "distributions", "next"),
    ("distributions", "hypothesis-testing", "next"),
    ("probability", "bayes-theorem", "next"),
    ("kinematics", "newtons-laws", "next"),
    ("newtons-laws", "momentum", "next"),
    ("newtons-laws", "work-energy", "next"),
    ("work-energy", "thermodynamics-laws", "related"),
    ("thermodynamics-laws", "entropy", "next"),
    ("electric-fields", "current-resistance", "next"),
    ("current-resistance", "ohms-law", "next"),
    ("ohms-law", "circuits", "next"),
    ("electric-fields", "magnetism", "next"),
    ("waves", "optics", "next"),
    ("derivatives", "kinematics", "related"),
    ("atomic-structure", "periodic-trends", "next"),
    ("periodic-trends", "chemical-bonding", "next"),
    ("chemical-bonding", "reaction-types", "next"),
    ("moles-stoichiometry", "reaction-types", "related"),
    ("reaction-types", "acids-bases", "next"),
    ("reaction-types", "equilibrium", "next"),
    ("equilibrium", "reaction-kinetics", "next"),
    ("organic-functional-groups", "reaction-mechanisms", "next"),
    ("cell-structure", "cell-transport", "next"),
    ("cell-transport", "photosynthesis", "next"),
    ("photosynthesis", "cellular-respiration", "next"),
    ("mitosis-meiosis", "dna-replication", "next"),
    ("dna-replication", "protein-synthesis", "next"),
    ("protein-synthesis", "mendelian-genetics", "related"),
    ("mendelian-genetics", "natural-selection", "next"),
    ("variables-types", "control-flow", "next"),
    ("control-flow", "functions-scope", "next"),
    ("functions-scope", "recursion", "next"),
    ("arrays-lists", "hash-maps", "next"),
    ("hash-maps", "big-o", "related"),
    ("recursion", "trees-graphs", "next"),
    ("big-o", "sorting-algorithms", "next"),
    ("trees-graphs", "dynamic-programming", "next"),
    ("http-apis", "databases-sql", "related"),
    ("neural-networks", "backpropagation", "next"),
    ("neural-networks", "embeddings", "next"),
    ("embeddings", "recommendation-systems", "next"),
    ("matrices", "neural-networks", "prerequisite"),
    ("derivatives", "backpropagation", "prerequisite"),
    ("supply-demand", "elasticity", "next"),
    ("elasticity", "market-structures", "next"),
    ("gdp", "inflation", "next"),
    ("inflation", "monetary-policy", "next"),
    ("world-war-one", "world-war-two", "next"),
    ("world-war-two", "cold-war", "next"),
    ("cold-war", "decolonisation", "related"),
    ("primary-sources", "historiography", "next"),
    ("weather-climate", "climate-change", "next"),
    ("research-methods", "cognitive-biases", "related"),
    ("classical-conditioning", "operant-conditioning", "next"),
    ("close-reading", "narrative-perspective", "next"),
    ("thesis-statements", "essay-structure", "next"),
    ("composition", "colour-theory", "next"),
    ("free-body-diagrams", "stress-strain", "next"),
]
