"""Content from the social/educational sources, and its concept links."""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import (
    Boolean,
    Computed,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    text,
)
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, TSVECTOR
from sqlalchemy.orm import Mapped, mapped_column, relationship

from novi.core.crypto import EncryptedJSON
from novi.models.base import Base, TimestampMixin, uuid_pk

PLATFORMS = (
    "bilibili",
    "xiaohongshu",
    "douyin",
    "kuaishou",
    "weibo",
    "tieba",
    "zhihu",
    "reddit",
    "youtube",
    "x",
)


class Content(Base, TimestampMixin):
    """One item in the feed.

    `is_sample` is not decoration. Until the real ingestion pipeline runs, the
    store is filled with generated placeholder items, and the flag is what
    keeps "this is a stand-in" a fact in the database rather than a note in a
    README that the UI cannot read. The client renders a marker for them.
    """

    __tablename__ = "content"
    __table_args__ = (
        Index("ix_content_search", "search_vector", postgresql_using="gin"),
        Index("ix_content_subject_quality", "subject_id", "quality"),
        Index("ix_content_tags", "tags", postgresql_using="gin"),
    )

    id: Mapped[uuid.UUID] = uuid_pk()
    platform: Mapped[str] = mapped_column(String(24), nullable=False, index=True)
    external_id: Mapped[str] = mapped_column(String(128), nullable=False)
    title: Mapped[str] = mapped_column(String(400), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False, default="")
    creator: Mapped[str] = mapped_column(String(120), nullable=False, default="")

    url: Mapped[str | None] = mapped_column(String(1024))
    media_url: Mapped[str | None] = mapped_column(String(1024))
    thumbnail_url: Mapped[str | None] = mapped_column(String(1024))
    # The client's masonry needs a card's height before it lays the card out,
    # so the cover's aspect ratio travels with the record rather than being
    # measured after load.
    thumbnail_ratio: Mapped[float] = mapped_column(Float, nullable=False, default=0.75)

    media_kind: Mapped[str] = mapped_column(String(16), nullable=False, default="post")
    language: Mapped[str] = mapped_column(String(16), nullable=False, default="en")
    duration_seconds: Mapped[int | None] = mapped_column(Integer)

    subject_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("subjects.id", ondelete="SET NULL"), index=True
    )
    topic: Mapped[str] = mapped_column(String(160), nullable=False, default="")
    tags: Mapped[list[str]] = mapped_column(ARRAY(String(48)), nullable=False, default=list)

    likes: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    comments: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    # 0..1, our own judgement of the item, independent of its popularity.
    quality: Mapped[float] = mapped_column(Float, nullable=False, default=0.5)
    difficulty: Mapped[int] = mapped_column(Integer, nullable=False, default=2)

    is_sample: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False, index=True)
    published_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    extra: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict, server_default="{}")

    # Generated by Postgres so it can never disagree with the row it indexes.
    search_vector: Mapped[str] = mapped_column(
        TSVECTOR,
        Computed(
            "setweight(to_tsvector('simple', coalesce(title, '')), 'A') || "
            "setweight(to_tsvector('simple', coalesce(topic, '')), 'B') || "
            "setweight(to_tsvector('simple', coalesce(description, '')), 'C')",
            persisted=True,
        ),
        nullable=False,
    )

    concept_links: Mapped[list[ContentConcept]] = relationship(
        back_populates="content", cascade="all, delete-orphan", lazy="selectin"
    )


# One item per platform id. Two feeds carrying the same video must not become
# two cards in the same column of the masonry.
Index("uq_content_platform_external", Content.platform, Content.external_id, unique=True)


class ContentConcept(Base):
    """Which concepts an item teaches, and how central each one is to it."""

    __tablename__ = "content_concepts"
    __table_args__ = (
        UniqueConstraint("content_id", "concept_id", name="uq_content_concepts_pair"),
    )

    id: Mapped[uuid.UUID] = uuid_pk()
    content_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("content.id", ondelete="CASCADE"), nullable=False, index=True
    )
    concept_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("concepts.id", ondelete="CASCADE"), nullable=False, index=True
    )
    relevance: Mapped[float] = mapped_column(Float, nullable=False, default=1.0)

    content: Mapped[Content] = relationship(back_populates="concept_links")
    concept: Mapped[object] = relationship("Concept", lazy="selectin")


class Discussion(Base, TimestampMixin):
    """A community thread — Reddit today, others later.

    Stored rather than proxied so a thread the tutor cited is still there when
    the learner comes back to it, and so translation and summary are computed
    once instead of on every open.
    """

    __tablename__ = "discussions"
    __table_args__ = (Index("ix_discussions_concept", "concept_id"),)

    id: Mapped[uuid.UUID] = uuid_pk()
    platform: Mapped[str] = mapped_column(String(24), nullable=False, default="reddit")
    external_id: Mapped[str] = mapped_column(String(128), nullable=False, unique=True)
    community: Mapped[str] = mapped_column(String(120), nullable=False, default="")
    title: Mapped[str] = mapped_column(String(400), nullable=False)
    body: Mapped[str] = mapped_column(Text, nullable=False, default="")
    author: Mapped[str] = mapped_column(String(120), nullable=False, default="")
    url: Mapped[str | None] = mapped_column(String(1024))
    language: Mapped[str] = mapped_column(String(16), nullable=False, default="en")
    upvotes: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    comment_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    concept_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("concepts.id", ondelete="SET NULL")
    )
    is_sample: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    # Filled lazily by the AI layer and cached: both are expensive and neither
    # changes once the thread is fetched.
    translation: Mapped[dict | None] = mapped_column(EncryptedJSON)
    summary: Mapped[dict | None] = mapped_column(EncryptedJSON)

    comments_: Mapped[list[DiscussionComment]] = relationship(
        back_populates="discussion", cascade="all, delete-orphan", lazy="selectin"
    )


class DiscussionComment(Base):
    __tablename__ = "discussion_comments"

    id: Mapped[uuid.UUID] = uuid_pk()
    discussion_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("discussions.id", ondelete="CASCADE"), nullable=False, index=True
    )
    author: Mapped[str] = mapped_column(String(120), nullable=False, default="")
    body: Mapped[str] = mapped_column(Text, nullable=False)
    upvotes: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    ordinal: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )

    discussion: Mapped[Discussion] = relationship(back_populates="comments_")
