# ruff: noqa: I001, UP007, UP035
# Written by alembic. Reformatting generated output on every
# autogenerate is churn with no reader.
"""initial schema

Revision ID: d9c26d2e7c0c
Revises: 
Create Date: 2026-09-07 22:00:19.296907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9c26d2e7c0c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=48), nullable=False),
    sa.Column('accent', sa.String(length=8), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects'))
    )
    op.create_index(op.f('ix_subjects_slug'), 'subjects', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('avatar_seed', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('onboarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('concepts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_concepts_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_concepts'))
    )
    op.create_index(op.f('ix_concepts_slug'), 'concepts', ['slug'], unique=True)
    op.create_index('ix_concepts_subject_difficulty', 'concepts', ['subject_id', 'difficulty'], unique=False)
    op.create_index(op.f('ix_concepts_subject_id'), 'concepts', ['subject_id'], unique=False)
    op.create_table('content',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=24), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('creator', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('media_url', sa.String(length=1024), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1024), nullable=True),
    sa.Column('thumbnail_ratio', sa.Float(), nullable=False),
    sa.Column('media_kind', sa.String(length=16), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('topic', sa.String(length=160), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=48)), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('quality', sa.Float(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('is_sample', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('simple', coalesce(title, '')), 'A') || setweight(to_tsvector('simple', coalesce(topic, '')), 'B') || setweight(to_tsvector('simple', coalesce(description, '')), 'C')", persisted=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_content_subject_id_subjects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content'))
    )
    op.create_index(op.f('ix_content_is_sample'), 'content', ['is_sample'], unique=False)
    op.create_index(op.f('ix_content_platform'), 'content', ['platform'], unique=False)
    op.create_index('ix_content_search', 'content', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_content_subject_id'), 'content', ['subject_id'], unique=False)
    op.create_index('ix_content_subject_quality', 'content', ['subject_id', 'quality'], unique=False)
    op.create_index('ix_content_tags', 'content', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('uq_content_platform_external', 'content', ['platform', 'external_id'], unique=True)
    op.create_table('passport_stamps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('subtitle', sa.String(length=200), nullable=False),
    sa.Column('icon', sa.String(length=48), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_passport_stamps_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_passport_stamps')),
    sa.UniqueConstraint('user_id', 'kind', 'key', name='uq_stamp_identity')
    )
    op.create_index(op.f('ix_passport_stamps_user_id'), 'passport_stamps', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=True),
    sa.Column('grade', sa.String(length=32), nullable=True),
    sa.Column('curriculum', sa.String(length=32), nullable=True),
    sa.Column('subject_order', postgresql.ARRAY(sa.String(length=48)), nullable=False),
    sa.Column('subject_interests', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('learning_preferences', postgresql.ARRAY(sa.String(length=48)), nullable=False),
    sa.Column('goals', postgresql.ARRAY(sa.String(length=48)), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('interests_decayed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_profiles'))
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('skills', postgresql.ARRAY(sa.String(length=48)), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('cover_seed', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_projects_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.create_index('ix_sessions_user_expires', 'sessions', ['user_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('concept_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_id', sa.UUID(), nullable=False),
    sa.Column('to_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['concepts.id'], name=op.f('fk_concept_edges_from_id_concepts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_id'], ['concepts.id'], name=op.f('fk_concept_edges_to_id_concepts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_concept_edges')),
    sa.UniqueConstraint('from_id', 'to_id', name='uq_concept_edges_pair')
    )
    op.create_index('ix_concept_edges_from', 'concept_edges', ['from_id'], unique=False)
    op.create_table('content_concepts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name=op.f('fk_content_concepts_concept_id_concepts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], name=op.f('fk_content_concepts_content_id_content'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_concepts')),
    sa.UniqueConstraint('content_id', 'concept_id', name='uq_content_concepts_pair')
    )
    op.create_index(op.f('ix_content_concepts_concept_id'), 'content_concepts', ['concept_id'], unique=False)
    op.create_index(op.f('ix_content_concepts_content_id'), 'content_concepts', ['content_id'], unique=False)
    op.create_table('content_likes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], name=op.f('fk_content_likes_content_id_content'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_content_likes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_likes')),
    sa.UniqueConstraint('user_id', 'content_id', name='uq_like_pair')
    )
    op.create_index(op.f('ix_content_likes_content_id'), 'content_likes', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_likes_user_id'), 'content_likes', ['user_id'], unique=False)
    op.create_table('discussions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=24), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('community', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=True),
    sa.Column('is_sample', sa.Boolean(), nullable=False),
    sa.Column('translation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name=op.f('fk_discussions_concept_id_concepts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discussions')),
    sa.UniqueConstraint('external_id', name=op.f('uq_discussions_external_id'))
    )
    op.create_index('ix_discussions_concept', 'discussions', ['concept_id'], unique=False)
    op.create_table('interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=True),
    sa.Column('concept_id', sa.UUID(), nullable=True),
    sa.Column('dwell_seconds', sa.Integer(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name=op.f('fk_interactions_concept_id_concepts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], name=op.f('fk_interactions_content_id_content'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_interactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interactions'))
    )
    op.create_index(op.f('ix_interactions_concept_id'), 'interactions', ['concept_id'], unique=False)
    op.create_index(op.f('ix_interactions_content_id'), 'interactions', ['content_id'], unique=False)
    op.create_index('ix_interactions_type_ts', 'interactions', ['kind', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_interactions_user_id'), 'interactions', ['user_id'], unique=False)
    op.create_index('ix_interactions_user_ts', 'interactions', ['user_id', 'occurred_at'], unique=False)
    op.create_table('learning_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('mastery', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('quiz_attempts', sa.Integer(), nullable=False),
    sa.Column('best_quiz_score', sa.Float(), nullable=False),
    sa.Column('last_touched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name=op.f('fk_learning_progress_concept_id_concepts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learning_progress_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_progress')),
    sa.UniqueConstraint('user_id', 'concept_id', name='uq_progress_pair')
    )
    op.create_index(op.f('ix_learning_progress_concept_id'), 'learning_progress', ['concept_id'], unique=False)
    op.create_index(op.f('ix_learning_progress_user_id'), 'learning_progress', ['user_id'], unique=False)
    op.create_index('ix_progress_user_mastery', 'learning_progress', ['user_id', 'mastery'], unique=False)
    op.create_table('project_concepts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name=op.f('fk_project_concepts_concept_id_concepts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_concepts_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_concepts')),
    sa.UniqueConstraint('project_id', 'concept_id', name='uq_project_concept')
    )
    op.create_index(op.f('ix_project_concepts_concept_id'), 'project_concepts', ['concept_id'], unique=False)
    op.create_index(op.f('ix_project_concepts_project_id'), 'project_concepts', ['project_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('mode', sa.String(length=24), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=True),
    sa.Column('concept_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name=op.f('fk_questions_concept_id_concepts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], name=op.f('fk_questions_content_id_content'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_questions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions'))
    )
    op.create_index('ix_questions_user_created', 'questions', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_questions_user_id'), 'questions', ['user_id'], unique=False)
    op.create_table('quizzes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name=op.f('fk_quizzes_concept_id_concepts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_quizzes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quizzes'))
    )
    op.create_index(op.f('ix_quizzes_concept_id'), 'quizzes', ['concept_id'], unique=False)
    op.create_index(op.f('ix_quizzes_user_id'), 'quizzes', ['user_id'], unique=False)
    op.create_table('saved_content',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('collection', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], name=op.f('fk_saved_content_content_id_content'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_saved_content_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_content')),
    sa.UniqueConstraint('user_id', 'content_id', name='uq_saved_pair')
    )
    op.create_index(op.f('ix_saved_content_content_id'), 'saved_content', ['content_id'], unique=False)
    op.create_index(op.f('ix_saved_content_user_id'), 'saved_content', ['user_id'], unique=False)
    op.create_table('ai_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('prompt_version', sa.String(length=24), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('feedback', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_ai_responses_question_id_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_responses'))
    )
    op.create_index(op.f('ix_ai_responses_question_id'), 'ai_responses', ['question_id'], unique=True)
    op.create_table('discussion_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('discussion_id', sa.UUID(), nullable=False),
    sa.Column('author', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussions.id'], name=op.f('fk_discussion_comments_discussion_id_discussions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discussion_comments'))
    )
    op.create_index(op.f('ix_discussion_comments_discussion_id'), 'discussion_comments', ['discussion_id'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quiz_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_index', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('fk_quiz_questions_quiz_id_quizzes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_questions'))
    )
    op.create_index(op.f('ix_quiz_questions_quiz_id'), 'quiz_questions', ['quiz_id'], unique=False)
    op.create_table('quiz_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quiz_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('selected_index', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], name=op.f('fk_quiz_results_question_id_quiz_questions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('fk_quiz_results_quiz_id_quizzes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_results')),
    sa.UniqueConstraint('quiz_id', 'question_id', name='uq_quiz_result_pair')
    )
    op.create_index(op.f('ix_quiz_results_quiz_id'), 'quiz_results', ['quiz_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_results_quiz_id'), table_name='quiz_results')
    op.drop_table('quiz_results')
    op.drop_index(op.f('ix_quiz_questions_quiz_id'), table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_index(op.f('ix_discussion_comments_discussion_id'), table_name='discussion_comments')
    op.drop_table('discussion_comments')
    op.drop_index(op.f('ix_ai_responses_question_id'), table_name='ai_responses')
    op.drop_table('ai_responses')
    op.drop_index(op.f('ix_saved_content_user_id'), table_name='saved_content')
    op.drop_index(op.f('ix_saved_content_content_id'), table_name='saved_content')
    op.drop_table('saved_content')
    op.drop_index(op.f('ix_quizzes_user_id'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_concept_id'), table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_index(op.f('ix_questions_user_id'), table_name='questions')
    op.drop_index('ix_questions_user_created', table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_project_concepts_project_id'), table_name='project_concepts')
    op.drop_index(op.f('ix_project_concepts_concept_id'), table_name='project_concepts')
    op.drop_table('project_concepts')
    op.drop_index('ix_progress_user_mastery', table_name='learning_progress')
    op.drop_index(op.f('ix_learning_progress_user_id'), table_name='learning_progress')
    op.drop_index(op.f('ix_learning_progress_concept_id'), table_name='learning_progress')
    op.drop_table('learning_progress')
    op.drop_index('ix_interactions_user_ts', table_name='interactions')
    op.drop_index(op.f('ix_interactions_user_id'), table_name='interactions')
    op.drop_index('ix_interactions_type_ts', table_name='interactions')
    op.drop_index(op.f('ix_interactions_content_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_concept_id'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_index('ix_discussions_concept', table_name='discussions')
    op.drop_table('discussions')
    op.drop_index(op.f('ix_content_likes_user_id'), table_name='content_likes')
    op.drop_index(op.f('ix_content_likes_content_id'), table_name='content_likes')
    op.drop_table('content_likes')
    op.drop_index(op.f('ix_content_concepts_content_id'), table_name='content_concepts')
    op.drop_index(op.f('ix_content_concepts_concept_id'), table_name='content_concepts')
    op.drop_table('content_concepts')
    op.drop_index('ix_concept_edges_from', table_name='concept_edges')
    op.drop_table('concept_edges')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index('ix_sessions_user_expires', table_name='sessions')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_passport_stamps_user_id'), table_name='passport_stamps')
    op.drop_table('passport_stamps')
    op.drop_index('uq_content_platform_external', table_name='content')
    op.drop_index('ix_content_tags', table_name='content', postgresql_using='gin')
    op.drop_index('ix_content_subject_quality', table_name='content')
    op.drop_index(op.f('ix_content_subject_id'), table_name='content')
    op.drop_index('ix_content_search', table_name='content', postgresql_using='gin')
    op.drop_index(op.f('ix_content_platform'), table_name='content')
    op.drop_index(op.f('ix_content_is_sample'), table_name='content')
    op.drop_table('content')
    op.drop_index(op.f('ix_concepts_subject_id'), table_name='concepts')
    op.drop_index('ix_concepts_subject_difficulty', table_name='concepts')
    op.drop_index(op.f('ix_concepts_slug'), table_name='concepts')
    op.drop_table('concepts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subjects_slug'), table_name='subjects')
    op.drop_table('subjects')
    # ### end Alembic commands ###
